# Generated by Django 5.1.4 on 2025-06-11 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lims_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reader',
            name='password',
        ),
        migrations.AddField(
            model_name='reader',
            name='reader_address',
            field=models.TextField(default=''),
        ),
    ]
