# Generated by Django 5.2.3 on 2025-09-01 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lims_app', '0002_remove_reader_password_reader_reader_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('available', models.BooleanField(default=True)),
            ],
        ),
    ]
