# Generated by Django 5.2.3 on 2025-09-01 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lims_app', '0003_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='books/'),
        ),
        migrations.AddField(
            model_name='book',
            name='genre',
            field=models.CharField(choices=[('fiction', 'Fiction'), ('nonfiction', 'Non-Fiction'), ('science', 'Science'), ('history', 'History'), ('fantasy', 'Fantasy'), ('biography', 'Biography')], default='fiction', max_length=30),
        ),
    ]
