# Generated by Django 5.2.3 on 2025-09-01 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lims_app', '0004_book_file_book_genre'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='book_covers/'),
        ),
        migrations.AlterField(
            model_name='book',
            name='genre',
            field=models.CharField(choices=[('fiction', 'Fiction'), ('nonfiction', 'Non-Fiction'), ('Comics', 'Comics'), ('Christian', 'Christian'), ('Children', 'Children'), ('Science', 'Science'), ('History', 'History'), ('Fantasy', 'Fantasy'), ('Biography', 'Biography')], default='fiction', max_length=30),
        ),
    ]
